Fix build on Windows/MinGW (haskell/ghcide#337)
This was causing the following error when trying to build under MinGW:

    [28 of 38] Compiling Development.IDE.Core.FileStore

    C:\Snapshot\src\ghcide\src\Development\IDE\Core\FileStore.hs:142:20: error:
        Not in scope: `Dir.getModificationTime'
        No module named `Dir' is imported.
        |
    142 |         do time <- Dir.getModificationTime f
        |                    ^^^^^^^^^^^^^^^^^^^^^^^