Update ghcide dependency for various plugins (#2368)
* hls-class-plugin: Update ghcide dependency

`hls-class-plugin-1.0.1.1` imports `Development.IDE.GHC.Compat.Util`, which doesn't exist until version `1.5.0`

```
Building library for hls-class-plugin-1.0.1.1..
[1 of 1] Compiling Ide.Plugin.Class ( src/Ide/Plugin/Class.hs, dist/build/Ide/Plugin/Class.o, dist/build/Ide/Plugin/Class.dyn_o )

src/Ide/Plugin/Class.hs:27:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
27 | import           Development.IDE.GHC.Compat.Util
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-fourmolu-plugin: Update ghcide dependency

```
src/Ide/Plugin/Fourmolu.hs:18:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import qualified Development.IDE.GHC.Compat.Util as S
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-hlint-plugin: Update ghcide dependency

```
src/Ide/Plugin/Hlint.hs:79:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Core’
    Perhaps you meant Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
79 | import           Development.IDE.GHC.Compat.Core                    hiding
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

* hls-ormolu-plugin: Update ghcide dependency

```
src/Ide/Plugin/Ormolu.hs:14:69: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘hsc_dflags’
   |
14 | import           Development.IDE.GHC.Compat      (moduleNameString, hsc_dflags)
   |                                                                     ^^^^^^^^^^

src/Ide/Plugin/Ormolu.hs:16:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
16 | import qualified Development.IDE.GHC.Compat.Util as S
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-retrie-plugin: Update ghcide dependency

```
src/Ide/Plugin/Retrie.hs:60:56: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘Outputable’
   |
60 |                                                        Outputable,
   |                                                        ^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:64:56: error:
    Module
    ‘Development.IDE.GHC.Compat’
    does not export
    ‘SourceText(..)’
   |
64 |                                                        SourceText (..),
   |                                                        ^^^^^^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:68:56: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘hm_iface’
   |
68 |                                                        hm_iface, isQual,
   |                                                        ^^^^^^^^

src/Ide/Plugin/Retrie.hs:68:66: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘isQual’
   |
68 |                                                        hm_iface, isQual,
   |                                                                  ^^^^^^

src/Ide/Plugin/Retrie.hs:69:56: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘isQual_maybe’
   |
69 |                                                        isQual_maybe,
   |                                                        ^^^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:72:56: error:
    Module
    ‘Development.IDE.GHC.Compat’
    does not export
    ‘nameModule_maybe’
   |
72 |                                                        nameModule_maybe,
   |                                                        ^^^^^^^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:73:56: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘nameRdrName’
   |
73 |                                                        nameRdrName, occNameFS,
   |                                                        ^^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:73:69: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘occNameFS’
   |
73 |                                                        nameRdrName, occNameFS,
   |                                                                     ^^^^^^^^^

src/Ide/Plugin/Retrie.hs:74:56: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘occNameString’
   |
74 |                                                        occNameString,
   |                                                        ^^^^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:79:56: error:
    Module ‘Development.IDE.GHC.Compat’ does not export ‘rdrNameOcc’
   |
79 |                                                        rdrNameOcc, rds_rules,
   |                                                        ^^^^^^^^^^

src/Ide/Plugin/Retrie.hs:81:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
81 | import           Development.IDE.GHC.Compat.Util      hiding (catch, try)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-retrie-plugin: Update ghcide dependency

```
src/Ide/Plugin/Splice.hs:48:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
48 | import qualified Development.IDE.GHC.Compat.Util as Util
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-stylish-haskell-plugin: Update ghcide dependency

```
src/Ide/Plugin/StylishHaskell.hs:13:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
13 | import qualified Development.IDE.GHC.Compat.Util as Util
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-tactics-plugin: Update ghcide dependency

```
src/Wingman/Metaprogramming/Lexer.hs:14:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Core’
    Perhaps you meant Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
14 | import           Development.IDE.GHC.Compat.Core (OccName, mkVarOcc)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Wingman/Range.hs:7:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Core’
    Perhaps you meant Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import           Development.IDE.GHC.Compat.Core
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Wingman/Range.hs:8:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
8 | import           Development.IDE.GHC.Compat.Util as FS
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Wingman/StaticPlugin.hs:12:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
12 | import Development.IDE.GHC.Compat.Util
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* hls-test-utils: Update ghcide dependency

```
src/Test/Hls.hs:52:51: error:
    Module
    ‘Development.IDE.Plugin.Test’
    does not export
    ‘TestRequest(GetBuildKeysBuilt)’
   |
52 | import           Development.IDE.Plugin.Test     (TestRequest (GetBuildKeysBuilt, WaitForIdeRule, WaitForShakeQueue),
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Test/Hls.hs:57:51: error:
    Module ‘Ide.PluginUtils’ does not export ‘idePluginsToPluginDesc’
   |
57 | import           Ide.PluginUtils                 (idePluginsToPluginDesc,
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^
```

Co-authored-by: Javier Neira <atreyu.bbb@gmail.com>