Disable build of shake-bench in stack 8.10.x
```
Error: While constructing the build
plan, the following exceptions were
encountered:

In the dependencies
for shake-bench-0.1.0.0:
    Chart-diagrams needed, but the stack
                   configuration has no
                   specified version
                   (latest matching
                   version is 1.9.3)
    diagrams needed, but the stack
             configuration has no
             specified version  (latest
             matching version is 1.4)
    diagrams-svg needed, but the stack
                 configuration has no
                 specified version
                 (latest matching
                 version is 1.4.3)
needed since shake-bench is a build
target.

```