Disable build of shake-bench in stack 8.6.x
Error:

Error: While constructing the build
plan, the following exceptions were
encountered:

In the dependencies
for diagrams-postscript-1.4.1:
    hashable-1.3.0.0 from stack
                     configuration does
                     not
                     match >=1.1 && <1.3
                     (latest matching
                     version is 1.2.7.0)
    lens-4.18 from stack configuration
              does not
              match >=4.0 && <4.18
              (latest matching version
              is 4.17.1)
needed due to shake-bench-0.1.0.0
               -> diagrams-postscript-1.4.1