ghcide needs prettyprinter 1.7
Since HLS 1.7, prettyprinter 1.7 is actually needed in order to build:
```
src/Development/IDE/Plugin/HLS.hs:44:1: error:
    Could not load module ‘Prettyprinter.Render.String’
    It is a member of the hidden package ‘prettyprinter-1.7.1’.
    Perhaps you need to add ‘prettyprinter’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘prettyprinter-1.7.1’.
    Perhaps you need to add ‘prettyprinter’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
44 | import           Prettyprinter.Render.String  (renderString)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build ghcide-1.9.0.0 (which is required by
exe:haskell-language-server-wrapper from haskell-language-server-1.9.0.0 and
exe:haskell-language-server from haskell-language-server-1.9.0.0). See the
build log above for details.
```