Add qualified imports in postfix position when `ImportQualifiedPost` and `WarnPrePositiveQualifiedModule` are set (#3399)
* Import qualified in postfix when applicable

* Dont import `EnumSet`

* Add `QualifiedImportStyle`

* Add qualified import test

* Ignore functional code action tests for windows-9.4.2

The test fails with:

test\functional\FunctionalCodeAction.hs:116:
expected: "Not in scope: \8216Control.when\8217\nNo module named \8216Control\8217 is imported."
but got: "Variable not in scope: when :: Bool -> IO () -> IO ()"

Seems like diagnostics for missing variables differ

* Add `importQualifiedPostTests`

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>